Criando estrutura para fluxo de cadastro de usuário
MiguelFernandesSantos/inkinvite pull request #1
Opened 2024-05-11 22:56 UTC by PedroDiSanti

**Criando estrutura para controle de criação de usuário**

2024-05-11 23:26 UTC, MiguelFernandesSantos commented on src/main/java/br/com/keycloak/domain/usuario/Usuario.java
> +    public static Usuario criar(String primeiroNomeUsuario, String segundoNomeUsuario, String loginUsuario, String emailUsuario, String senhaUsuario) {
Na classe de domínio Usuario, os metodos Factory (criar e carregar) possuem os parâmetros:

- primeiroNomeUsuario
- segundoNomeUsuario
- loginUsuario
- emailUsuario
- senhaUsuario

Entretanto o método já esta dentro da classe Usuario, tornando o uso de "Usuario" no nome do parâmetro um pouco redundante.

2024-05-11 23:29 UTC, MiguelFernandesSantos commented on src/main/java/br/com/keycloak/application/component/UsuarioComponent.java
> +package br.com.keycloak.application.component;
Precisamos decidir se nosso "domínio" vai ser "br.com.keycloak" ou "br.com.inkinvite" (inkinvite por conta do nome do projeto)

2024-05-11 23:45 UTC, MiguelFernandesSantos commented on src/main/java/br/com/keycloak/infrastructure/repo/usuario/UsuarioFactory.java
> +            resultSet.getString("primeiroNomeUsuario"),
Dentro dos métodos get do ResultSet, está sendo utilizado o estilo camelCase para nomear colunas. No entanto, em certos casos, o MySQL pode ter dificuldade em distinguir entre maiúsculas e minúsculas, o que pode levar a erros.

Para evitar problemas, é recomendável adotar o estilo pascal_case ao nomear colunas ao interagir com o MySQL, especialmente em ambientes Windows ou em versões mais antigas do MySQL.

2024-05-11 23:46 UTC, MiguelFernandesSantos commented on src/main/java/br/com/keycloak/infrastructure/repo/usuario/UsuarioFactory.java
> +    public static List<Usuario> mapearObras(ResultSet resultSet) throws SQLException, ParseException {
Apesar de ser um Factory da classe Usuario, os métodos estão sendo nomeados de forma relacionada a obras.

2024-05-11 23:50 UTC, MiguelFernandesSantos commented on src/main/java/br/com/keycloak/domain/usuario/UsuarioCompleto.java
> +    private Avaliacao avaliacao;
Na classe UsuarioCompleto, existem dois atributos privados que não são inicializados nem utilizados.

Realmente é necessário a classe UsuarioCompleto no momento?

2024-05-11 23:52 UTC, MiguelFernandesSantos commented on src/main/java/br/com/keycloak/application/usecase/UsuarioUseCase.java
> +            usuarioRepo.salvar(usuario);
Antes de salvar um novo usuário, seria importante verificar se o "login" escolhido já foi utilizado por outros usuários?

2024-05-11 23:55 UTC, MiguelFernandesSantos commented on src/main/java/br/com/keycloak/interfaces/resources/UsuarioResources.java
> +    public Response criarusuario(UsuarioDto usuario) {
O nome do método não está seguindo a convenção camelCase.

2024-05-11 23:57 UTC, MiguelFernandesSantos commented on src/main/java/br/com/keycloak/domain/usuario/UsuarioCompleto.java
> +    public String getPrimeiroNomeUsuario() {
O método sobrescrito é idêntico ao da classe pai.

2024-05-12 00:01 UTC, MiguelFernandesSantos requested changes
Fiz alguns comentários que acharia interesse dar uma olhada e ver se faz sentido ou não para você.

2024-05-12 11:25 UTC, PedroDiSanti commented on src/main/java/br/com/keycloak/domain/usuario/Usuario.java
> +    public static Usuario criar(String primeiroNomeUsuario, String segundoNomeUsuario, String loginUsuario, String emailUsuario, String senhaUsuario) {
Corrigido.

2024-05-12 11:26 UTC, PedroDiSanti commented on src/main/java/br/com/keycloak/application/component/UsuarioComponent.java
> +package br.com.keycloak.application.component;
Como falamos, devemos juntar o domínio. Depois, me fala como devo fazer isso que eu coloco tudo em "br.com.inkinvite".

2024-05-12 11:26 UTC, PedroDiSanti commented on src/main/java/br/com/keycloak/infrastructure/repo/usuario/UsuarioFactory.java
> +            resultSet.getString("primeiroNomeUsuario"),
Corrigido.

2024-05-12 11:26 UTC, PedroDiSanti commented on src/main/java/br/com/keycloak/infrastructure/repo/usuario/UsuarioFactory.java
> +    public static List<Usuario> mapearObras(ResultSet resultSet) throws SQLException, ParseException {
Corrigido.

2024-05-12 11:26 UTC, PedroDiSanti commented on src/main/java/br/com/keycloak/domain/usuario/UsuarioCompleto.java
> +    private Avaliacao avaliacao;
Removido.

2024-05-12 11:27 UTC, PedroDiSanti commented on src/main/java/br/com/keycloak/application/usecase/UsuarioUseCase.java
> +            usuarioRepo.salvar(usuario);
Sim, será necessário. Porém, neste PR, só quero deixar uma estrutura funcional para o fluxo do Keycloak para, depois, começar a implementar a lógica.

2024-05-12 11:27 UTC, PedroDiSanti commented on src/main/java/br/com/keycloak/interfaces/resources/UsuarioResources.java
> +    public Response criarusuario(UsuarioDto usuario) {
Corrigido.

2024-05-12 11:27 UTC, PedroDiSanti commented on src/main/java/br/com/keycloak/domain/usuario/UsuarioCompleto.java
> +    public String getPrimeiroNomeUsuario() {
Removido.

2024-05-12 15:27 UTC, MiguelFernandesSantos commented on src/main/java/br/com/keycloak/application/component/UsuarioComponent.java
> +package br.com.keycloak.application.component;
Posso fazer isso se quiser, mas seria apenas uma questão de mover todas as suas classes criadas para dentro de br.com.inkinvite, organizando-as em suas respectivas pastas, como:

Classes de domínio para a pasta dominio
Componentes para a pasta component
E assim por diante

2024-05-14 22:20 UTC, merged