Implementado criação de usuário no keycloak e banco
MiguelFernandesSantos/inkinvite pull request #2
Opened 2024-05-19 15:05 UTC by PedroDiSanti

**Principais Alterações**

**Refatoração do Cliente Keycloak**

1. Introdução da classe KeycloakProvider como singleton para configuração e criação do cliente Keycloak, centralizando os detalhes de configuração e melhorando a manutenção do código.
2. Utilização de injeção de dependência para o KeycloakProvider em UsuarioResources, aumentando a testabilidade e desacoplamento dos componentes.

**Melhoria no Endpoint de Criação de Usuários**

1. O método criarUsuario foi modificado para utilizar o KeycloakProvider, tratando a criação de usuários no Keycloak e no domínio da aplicação de forma unificada, com verificação de sucesso antes de proceder com operações locais.

**Gerenciamento de Representação de Usuário e Credenciais**

1. Criação do método createUserRepresentation para construir objetos UserRepresentation a partir de UsuarioDto, e método createPasswordCredentials para configuração de credenciais de senha, enfatizando a responsabilidade única e clareando a gestão do código.

2024-05-19 15:46 UTC, MiguelFernandesSantos commented on src/main/java/br/com/inkinvite/interfaces/resources/UsuarioResources.java
> +class KeycloakProvider {
A classe KeycloakProvider não deveria estar dentro do arquivo UsuarioResources, pois UsuarioResources esta presente na pasta 'Interfaces', que deve se concentrar apenas na entrada ou saída de dados da aplicação. 

O KeycloakProvider deveria ser movida para um arquivo separado, em um pacote mais apropriado.

2024-05-19 15:47 UTC, MiguelFernandesSantos commented on src/main/java/br/com/inkinvite/interfaces/resources/UsuarioResources.java
> +    private String kcServerUrl;
Os atributos da classe KeycloakProvider não precisam iniciar com 'kc'. Como esses atributos já estão dentro de uma classe chamada KeycloakProvider, o prefixo 'kc' é redundante.

2024-05-19 15:52 UTC, MiguelFernandesSantos commented on src/main/java/br/com/inkinvite/interfaces/resources/UsuarioResources.java
> +    private UserRepresentation createUserRepresentation(UsuarioDto usuario) {
O método createUserRepresentation na classe UsuarioResources viola o princípio da responsabilidade única (SRP).

A UsuarioResources deveria se concentrar apenas em receber e tratar requisições HTTP, porem com esse método atualmente também está lidando com a conversão/instanciação de objetos. 

Fazendo com que a classe mude quando precise lidar com http ou a conversão desses objetos.

Essas responsabilidades deveriam estar separadas em outra classe.

2024-05-19 16:01 UTC, MiguelFernandesSantos commented on src/main/java/br/com/inkinvite/interfaces/resources/UsuarioResources.java
> +            Response response = usersResource.create(user);
Atualmente, a criação do usuário está sendo realizada em dois lugares distintos: UsuarioResources (que faz a requisição para o Keycloak criar o usuário) e UsuarioRepo (que cria o usuário no banco de dados quando o Keycloak retorna sucesso). 

Seria mais adequado centralizar essa lógica em um único serviço especializado em criação de usuários. Por exemplo, podemos introduzir um UsuarioService que encapsula toda a lógica de criação, incluindo a integração com o Keycloak e a persistência no banco de dados. Isso garantiria uma separação clara de responsabilidades.

2024-05-19 16:04 UTC, MiguelFernandesSantos requested changes
São apenas comentários, caso ache que não tem necessariedade eu apenas aceito.

2024-05-20 14:59 UTC, PedroDiSanti commented on src/main/java/br/com/inkinvite/interfaces/resources/UsuarioResources.java
> +class KeycloakProvider {
Formatei o projeto e movi este Singleton para o package br.com.inkinvite.security.

2024-05-20 15:00 UTC, PedroDiSanti commented on src/main/java/br/com/inkinvite/interfaces/resources/UsuarioResources.java
> +    private String kcServerUrl;
Alterei os nomes das variáveis.

2024-05-20 15:00 UTC, PedroDiSanti commented on src/main/java/br/com/inkinvite/interfaces/resources/UsuarioResources.java
> +    private UserRepresentation createUserRepresentation(UsuarioDto usuario) {
Certo. Criei uma pasta converter e movi esta classe para o br.com.inkinvite.application.converter.

Com isso, criei uma nova classe chamada UserRepresentationConverter que lidará com a conversão de um UsuarioDto para um UserRepresentation. Por fim, atualizei a classe UsuarioResources para usar essa nova classe.

2024-05-20 15:00 UTC, PedroDiSanti commented on src/main/java/br/com/inkinvite/interfaces/resources/UsuarioResources.java
> +            Response response = usersResource.create(user);
Utilizei o UsuarioService para encapsular toda a lógica de criação de usuários, incluindo a interação com o Keycloak e a persistência no banco de dados. 
Com isso, a UsuarioResources concentra apenas no tratamento de requisições HTTP e delega a criação de usuários ao UsuarioService.

2024-05-20 15:01 UTC, PedroDiSanti commented
> São apenas comentários, caso ache que não tem necessariedade eu apenas aceito.

Apliquei as alterações pedidas. Por favor, veja se concorda e, caso eu tenha feito alguma estrutura errada, me avise para corrigir.

Obrigado!

2024-05-20 16:21 UTC, MiguelFernandesSantos commented on src/main/java/br/com/inkinvite/application/converter/UserRepresentationConverter.java
> +public class UserRepresentationConverter {
Na arquitetura de camadas do projeto o "Application" e o "Domain" não devem possuir nenhuma tecnologia/iib (Somente deve possuir Java puro).

Atualmente foi movido o "UserRepresentationConverter" para dentro do "Application" porem o mesmo utiliza as libs do KeyClock e as anotações do proprio Quarkus como "ApplicationScoped".

2024-05-20 16:21 UTC, MiguelFernandesSantos commented on src/main/java/br/com/inkinvite/application/service/UsuarioService.java
> +public class UsuarioService {
Não esta respeitando o DDD e as camadas do projeto.

2024-05-20 17:12 UTC, PedroDiSanti commented on src/main/java/br/com/inkinvite/application/converter/UserRepresentationConverter.java
> +public class UserRepresentationConverter {
Certo. Então, para corrigir isso, eu posso mover a classe UserRepresentationConverter para a camada "infrastructure", removendo as dependências de tecnologia da camada "Application".

Com isso teria o pacote br.com.inkinvite.infrastructure.converter. Correto?

2024-05-20 17:22 UTC, PedroDiSanti commented on src/main/java/br/com/inkinvite/application/service/UsuarioService.java
> +public class UsuarioService {
Por favor, como eu faria para que esta implementação esteja com os padrões do projeto?

Ao meu ver, talvez adicionar a lógica de negócio específica do domínio. Ficando assim:

- UsuarioDomain: Implementa a lógica de negócio específica do domínio.

- UsuarioService: Orquestra a criação de usuários, chamando tanto o serviço de domínio quanto lidando com a persistência e integração com Keycloak.

- UsuarioResources: Continua focado apenas em receber e tratar as requisições HTTP.

2024-05-28 22:22 UTC, merged