Feature - Realizar login
MiguelFernandesSantos/inkinvite pull request #3
Opened 2024-05-31 23:19 UTC by PedroDiSanti

- Um usuário passará seu login e senha via requisição;
- Essa requisição será recebida pelo backend e tratada de maneira adequada;
- Uma conexão será feita ao keycloak. Caso exista um usuário válido para a combinação de login e senha um token JWT será retornado;
- Este token JWT será utilizado para os requests nas demais APIs;

2024-06-01 00:34 UTC, MiguelFernandesSantos commented on src/main/java/br/com/inkinvite/interfaces/resources/LoginResources.java
> +            return Response.status(Response.Status.CONFLICT).entity(result).type(MediaType.TEXT_PLAIN).build();
Quando da sucesso você esta retornando o status 409, teria um motivo para retornar um código de conflito?

2024-06-01 00:49 UTC, MiguelFernandesSantos commented on src/main/java/br/com/inkinvite/domain/login/Login.java
> +public class Login extends Agregado {
O Login ele não se enquadra como um objeto de domínio (Ele não é uma entidade afinal não tem um identificador único, ele não é um agregado porque não possui outra entidade como atributo, ele poderia até ser considerado um objeto de valor mas acredito que não seria uma boa pratica colocar como objeto de valor)

Em minha opinião seria mais coeso se a classe Login/CabecalhoLogin não existisse e fosse passado apenas como parâmetros dos métodos: Login e senha separadamente sem a necessidade de criar um objeto do tipo Login.

O ato de logar ele não representa uma regra de negocio/domínio.

Segue alguns links que comentam sobre:
https://lgertel.medium.com/objetos-de-valor-e-entidades-ceb120b2e037

https://elemarjr.com/clube-de-estudos/artigos/agregados-em-domain-driven-design-organizando-a-complexidade-do-dominio/#:~:text=O%20que%20%C3%A9%20um%20agregado,garantir%20a%20consist%C3%AAncia%20dos%20dados.

2024-06-01 00:55 UTC, MiguelFernandesSantos commented on src/main/java/br/com/inkinvite/application/repo/LoginRepo.java
> +public interface LoginRepo {
No Domain Driven Design um repositório esta ligado sempre com um agregado (em outro comentário sobre a classe Login eu comento sobre o porque o Login não ser considerado um objeto de domínio e ao nem entidade)

2024-06-01 01:03 UTC, MiguelFernandesSantos commented on src/main/java/br/com/inkinvite/application/component/LoginComponent.java
> +public class LoginComponent {
Chamar esse Component de "LoginComponent" deixa ele muito preso a somente o ato de logar, poderia ser interessante chamá-lo de "AutenticacaoComponent", permitindo que ele lide com mais cenários relacionados a autenticação (Como Login, troca de senha, esqueci minha senha, exclusão de conta etc)

No cenário que cada Component tenha apenas um método (como o recuperarLogin do LoginComponent) a longo prazo o sistema ficaria com uma granularidade tão grande que poderia ser difícil de dar manutenção.

2024-06-01 01:07 UTC, MiguelFernandesSantos commented on src/main/java/br/com/inkinvite/infrastructure/security/KeycloakProvider.java
> +    public Keycloak obterClientKeycloakPorLogin(String username, String password) {
Os nomes dos parâmetros estão em inglês, para melhor consistência poderia ser colocado em português os parâmetros.

2024-06-01 01:10 UTC, MiguelFernandesSantos commented on src/main/java/br/com/inkinvite/infrastructure/repo/login/LoginJdbcRepo.java
> +    public String recuperar(Login login) {
O nome do método "recuperar" não é algo que deixa claro o que esta sendo realizado no seu código, poderia ser "logar" para que seja fácil de entender somente ao ler o nome do método.

Em conjunto o método possui a anotação "@Transactional" que é utilizada para criar uma transação com o banco de dados, porem o método não utiliza o banco de dados.

2024-06-01 01:23 UTC, MiguelFernandesSantos commented on src/main/java/br/com/inkinvite/infrastructure/repo/login/LoginJdbcRepo.java
> +        } catch (Exception e) {
Atualmente qualquer erro que ocorra é apenas retornado para quem fez a requisição (Basicamente qualquer erro no fluxo de Login retorna um Http 500 internal server error).

Porem para melhor tratamento no Front-end seria interessante realizar a validação de quando o usuário não existe e retornar um 404 por exemplo para que o Front-End possa tratar de outra forma esse erro.

Esse fluxo poderia lançar por exemplo uma Expcepion "UsuarioNaoExiste" que é tratado no resource e convertido para 404.

2024-06-01 01:25 UTC, MiguelFernandesSantos requested changes
Fiz alguns comentários, poderia ver quais fazem sentido para você e qual não faz?

E novamente faço o levantamento que grande parte é sobre o DDD, porem se o melhor é apenas funcionar pode ignorar.

2024-06-01 09:05 UTC, PedroDiSanti commented on src/main/java/br/com/inkinvite/domain/login/Login.java
> +public class Login extends Agregado {
Então, seria algo como mandar um request apenas com o login e senha e, na camada de LoginResources, ou melhor, AutenticacaoResources, eu receberia estes campos e faria o fluxo em uma service.

Isso está correto?

2024-06-01 09:29 UTC, PedroDiSanti commented on src/main/java/br/com/inkinvite/interfaces/resources/LoginResources.java
> +            return Response.status(Response.Status.CONFLICT).entity(result).type(MediaType.TEXT_PLAIN).build();
Eu tinha copiado da outra classe e esquecido de alterar.

Alterei para 200, OK.

2024-06-01 09:30 UTC, PedroDiSanti commented on src/main/java/br/com/inkinvite/application/repo/LoginRepo.java
> +public interface LoginRepo {
Alterei os nomes.

2024-06-01 09:30 UTC, PedroDiSanti commented on src/main/java/br/com/inkinvite/application/component/LoginComponent.java
> +public class LoginComponent {
Alterei os nomes.

2024-06-01 09:30 UTC, PedroDiSanti commented on src/main/java/br/com/inkinvite/infrastructure/security/KeycloakProvider.java
> +    public Keycloak obterClientKeycloakPorLogin(String username, String password) {
Traduzi as variáveis.

2024-06-01 09:30 UTC, PedroDiSanti commented on src/main/java/br/com/inkinvite/infrastructure/repo/login/LoginJdbcRepo.java
> +    public String recuperar(Login login) {
Alterado e corrigido.

2024-06-01 09:31 UTC, PedroDiSanti commented on src/main/java/br/com/inkinvite/infrastructure/repo/login/LoginJdbcRepo.java
> +        } catch (Exception e) {
Criei um fluxo para um usuário não encontrado.

2024-06-01 12:12 UTC, MiguelFernandesSantos commented on src/main/java/br/com/inkinvite/domain/login/Login.java
> +public class Login extends Agregado {
Basicamente eu acho que o AutenticacaoResources ele pode receber o "LoginDto" (Porque DTO ele não tem tanta regras, por ser um Data transfer object) porem esse DTO ele não tem um domínio ligado com ele.

Acho que seria mais interessante se você passasse como parâmetro os dois atributos do DTO separadamente para o Component e fosse descendo eles até o service.

2024-06-01 12:25 UTC, MiguelFernandesSantos commented on src/main/java/br/com/inkinvite/infrastructure/repo/login/LoginJdbcRepo.java
> +        } catch (Exception e) {
Beleza, agora como tem o tratamento para usuário não existe seria interessante ter o tratamento para quando a senha esta incorreta.

Se ele mandou o password incorreto ele poderia retornar um 400 (Bad Request) ou 406 (Not Acceptable), porque é o caso do usuário existir mas a senha estar incorreta.

2024-06-02 09:54 UTC, PedroDiSanti commented on src/main/java/br/com/inkinvite/domain/login/Login.java
> +public class Login extends Agregado {
Alterado.

Mudei para o tipo service e alterei as pastas do projeto. Também comecei a passar os parâmetros login e senha sem usar o DTO.

2024-06-02 09:54 UTC, PedroDiSanti commented on src/main/java/br/com/inkinvite/application/repo/LoginRepo.java
> +public interface LoginRepo {
Alterado.

2024-06-02 10:50 UTC, PedroDiSanti commented on src/main/java/br/com/inkinvite/infrastructure/repo/login/LoginJdbcRepo.java
> +        } catch (Exception e) {
Criei o erro 400 caso o usuário seja inválido no KeyCloak. Ou seja, tenha um username válido e uma senha incorreta.

2024-06-02 13:53 UTC, MiguelFernandesSantos commented on src/main/java/br/com/inkinvite/application/usecase/AutenticacaoUseCase.java
> +    private final AutenticacaoService authRepo;
O nome do atributo ainda esta "authRepo" seria correto algo como "authService", ou em português "autenticacaoService"

2024-06-02 13:55 UTC, MiguelFernandesSantos commented on src/main/java/br/com/inkinvite/interfaces/resources/AutenticacaoResources.java
> +    public AutenticacaoResources(AutenticacaoService authRepo, LogService logService) {
O nome do atributo ainda esta "authRepo" seria correto algo como "authService", ou em português "autenticacaoService"

2024-06-02 14:00 UTC, MiguelFernandesSantos commented on src/main/java/br/com/inkinvite/infrastructure/service/AutenticacaoJdbcService.java
> +    public String logar(String login, String senha) {
Nesse método "logar" você tem um "catch" para "UsuarioNaoEncontrado" e "UsuarioInvalido", porem ambas estendem "DominioException" (ou seja ambos são DominioException).

Poderia simplificar esses dois catch com apenas a super classe, exemplo:

       try {
            return validarLogin(login, senha);
        } catch (DominioException e) {
            throw e;
        } catch (Exception e) {
            throw new RuntimeException(e);
        }

2024-06-02 14:03 UTC, MiguelFernandesSantos commented on src/main/java/br/com/inkinvite/infrastructure/service/AutenticacaoJdbcService.java
> +            throw new UsuarioNaoEncontrado();
No tratamento das exceptions "UsuarioNaoEncontrado" e "UsuarioInvalido" estão sendo instanciados uma nova instancia dos erros, o mais correto apenas retornar o erro para cima porque você já tem uma instancia (que seria no caso "e").

2024-06-02 14:03 UTC, MiguelFernandesSantos commented on src/main/java/br/com/inkinvite/interfaces/resources/AutenticacaoResources.java
> +    public Response login(Map<String, String> credentials) {
O nome do parâmetro esta em inglês.

2024-06-02 14:06 UTC, MiguelFernandesSantos commented on src/main/java/br/com/inkinvite/infrastructure/service/AutenticacaoJdbcService.java
> +            if (keycloakError.getResponse().getStatus() == 401) {
esse bloco de código presente dentro do primeiro Catch:

            if (keycloakError.getResponse().getStatus() == 401) {
                throw new UsuarioInvalido();
            } else if (keycloakError.getResponse().getStatus() == 404) {
                throw new UsuarioNaoEncontrado();
            } else {
                throw new RuntimeException(keycloakError);
            }
            
Poderia ser separado em outro método responsável apenas por realizar a conversão do código http retornado pelo KeyClock.

Isso simplificaria a leitura do método "validarLogin".

2024-06-02 14:08 UTC, MiguelFernandesSantos requested changes
Fiz alguns pequenos comentários sobre nome de variáveis/atributos, utilização de super classe para tratamento dos erros, separação de métodos e sobre a criação de uma nova instancia dos erros que pode ser desnecessário.

2024-06-02 14:48 UTC, PedroDiSanti commented on src/main/java/br/com/inkinvite/application/usecase/AutenticacaoUseCase.java
> +    private final AutenticacaoService authRepo;
Alterado.

2024-06-02 14:48 UTC, PedroDiSanti commented on src/main/java/br/com/inkinvite/interfaces/resources/AutenticacaoResources.java
> +    public AutenticacaoResources(AutenticacaoService authRepo, LogService logService) {
Alterado.

2024-06-02 14:48 UTC, PedroDiSanti commented on src/main/java/br/com/inkinvite/infrastructure/service/AutenticacaoJdbcService.java
> +    public String logar(String login, String senha) {
Alterado.

2024-06-02 14:48 UTC, PedroDiSanti commented on src/main/java/br/com/inkinvite/interfaces/resources/AutenticacaoResources.java
> +    public Response login(Map<String, String> credentials) {
Traduzido.

2024-06-02 14:48 UTC, PedroDiSanti commented on src/main/java/br/com/inkinvite/infrastructure/service/AutenticacaoJdbcService.java
> +            if (keycloakError.getResponse().getStatus() == 401) {
Criei um método "tratarErroHttpKeycloak" para englobar esta lógica.

2024-06-02 14:50 UTC, merged