Feat/esqueci minha senha
MiguelFernandesSantos/inkinvite pull request #5
Opened 2024-06-17 12:47 UTC by PedroDiSanti

Feito nesta task:
- Criação de fluxo de reset de senha;
- Instalação de email de aplicação via Keycloak para envio de configuração;
- Nova senha setada para usuário via mecanismo de reset password do Keycloak;

2024-06-18 02:46 UTC, MiguelFernandesSantos commented on src/main/java/br/com/inkinvite/application/usecase/AutenticacaoUseCase.java
> +        start("Iniciando recuperacao de usuario " + login);
O fluxo é "esqueci minha senha" porem os Logs não aparentam ser relacionados a esses fluxos.

2024-06-18 02:47 UTC, MiguelFernandesSantos commented on src/main/java/br/com/inkinvite/application/usecase/AutenticacaoUseCase.java
> +    public void esqueciSenha(String login) {
O nome do parâmetro "login" não deixa muito claro o que é esperado nesse campo.

Seria o e-mail? um identificador único? seria interessante achar uma variável que deixasse mais claro o que é esperado.

2024-06-18 02:49 UTC, MiguelFernandesSantos commented on src/main/java/br/com/inkinvite/infrastructure/service/AutenticacaoJdbcService.java
> +    public void esqueciSenha(String email) {
O corpo desse método não realiza nada alem de chamar o outro método "validarEsqueciSenha", seria interessante unificar esses dois métodos em apenas um.

2024-06-18 02:51 UTC, MiguelFernandesSantos commented on src/main/java/br/com/inkinvite/infrastructure/service/AutenticacaoJdbcService.java
> +                throw new UsuarioNaoEncontrado();
Você esta lançando a exceção "UsuarioNaoEncontrado" porem o catch (Exception e) da linha 69 até 71 o transforma em uma "RuntimeException", fazendo com que se perca a exception personalizada.

2024-06-18 02:52 UTC, MiguelFernandesSantos requested changes
Poderia analisar os pontos que levantei e aproveitar e puxar o que tem na master para sua branch?

2024-06-19 12:31 UTC, PedroDiSanti commented on src/main/java/br/com/inkinvite/application/usecase/AutenticacaoUseCase.java
> +    public void esqueciSenha(String login) {
O parâmetro necessário para esta funcionalidade seria o "username" definido no keycloak. No fluxo geral, estou chamando de login.

Não queria passar o nome de username porque ficaria a mistura do inglês e português. O que acha de passar credencialUsuario ou algo assim?

2024-06-19 12:44 UTC, PedroDiSanti commented on src/main/java/br/com/inkinvite/infrastructure/service/AutenticacaoJdbcService.java
> +                throw new UsuarioNaoEncontrado();
A exceção do UsuarioNaoEncontrado é lançada quando o user volta como nulo, acho que ele não cai no catch genérico para outros erros. Isso está errado?

2024-06-19 12:45 UTC, PedroDiSanti commented on src/main/java/br/com/inkinvite/infrastructure/service/AutenticacaoJdbcService.java
> +    public void esqueciSenha(String email) {
Juntei os métodos.

2024-06-19 12:45 UTC, PedroDiSanti commented on src/main/java/br/com/inkinvite/application/usecase/AutenticacaoUseCase.java
> +        start("Iniciando recuperacao de usuario " + login);
Corrigido.

2024-06-19 12:46 UTC, PedroDiSanti commented
> Poderia analisar os pontos que levantei e aproveitar e puxar o que tem na master para sua branch?

Fiz o merge das branchs.

2024-06-19 16:35 UTC, MiguelFernandesSantos commented on src/main/java/br/com/inkinvite/infrastructure/service/AutenticacaoJdbcService.java
> +                throw new UsuarioNaoEncontrado();
Na realidade, a UsuarioNaoEncontrado é uma exceção criada por você que estende a exceção DominioException. Esta, por sua vez, estende RuntimeException, que é uma subclasse de Exception.

Segue a hierarquia das exceções:

Exception
 └── RuntimeException
      └── DominioException
           └── UsuarioNaoEncontrado

Por conta de você fazer apenas um catch genérico de Exception, devido ao polimorfismo, UsuarioNaoEncontrado é capturada e convertida para uma RuntimeException.

Para evitar a conversão dos erros de domínio, seria interessante capturar as exceções dessa forma:

try {
    // Seu código
} catch (DominioException e) {
    throw e;
} catch (Exception e) {
    throw new RuntimeException(e);
}

2024-06-19 16:45 UTC, MiguelFernandesSantos commented on src/main/java/br/com/inkinvite/application/usecase/AutenticacaoUseCase.java
> +    public void esqueciSenha(String login) {
Acho que por mim tranquilo ser credencialUsuario

2024-06-20 13:16 UTC, PedroDiSanti commented on src/main/java/br/com/inkinvite/infrastructure/service/AutenticacaoJdbcService.java
> +                throw new UsuarioNaoEncontrado();
Entendi. Fiz a correção e adicionei o tratamento 404 na rota também, que estava sem.

2024-06-20 13:17 UTC, PedroDiSanti commented on src/main/java/br/com/inkinvite/application/usecase/AutenticacaoUseCase.java
> +    public void esqueciSenha(String login) {
Alterei.

2024-06-20 14:24 UTC, merged